#------------------------------------------------------------------------------
# General variables
#------------------------------------------------------------------------------
variable "app" {
  description = "(Required) App name."
  type        = string
}

variable "env" {
  description = "(Required) Environment."
  type        = string
}

#------------------------------------------------------------------------------
# SNS
#------------------------------------------------------------------------------
variable "name" {
  description = "(Optional) The friendly name for the SNS topic. By default generated by Terraform."
  type        = string
  default     = ""
}

variable "name_prefix" {
  description = "(Optional) The friendly name for the SNS topic. Conflicts with name."
  type        = string
  default     = ""
}

variable "display_name" {
  description = "(Optional) The display name for the SNS topic."
  type        = string
  default     = ""
}

variable "policy" {
  description = "(Optional) The fully-formed AWS policy as JSON. For more information about building AWS IAM policy documents with Terraform, see the AWS IAM Policy Document Guide."
  type        = string
  default     = ""
}

variable "delivery_policy" {
  description = "(Optional) The SNS delivery policy. More on AWS documentation."
  type        = string
  default     = ""
}

variable "kms_master_key_id" {
  description = "(Optional) The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information, see Key Terms."
  type        = string
  default     = ""
}

variable "tags" {
  description = "(Optional) Key-value map of resource tags."
  type        = string
  default     = ""
}

#------------------------------------------------------------------------------
# Application
#------------------------------------------------------------------------------
variable "application_success_feedback_role_arn" {
  description = "(Optional) The IAM role permitted to receive success feedback for this topic."
  type        = string
  default     = ""
}

variable "application_success_feedback_sample_rate" {
  description = "(Optional) Percentage of success to sample."
  type        = string
  default     = ""
}

variable "application_failure_feedback_role_arn" {
  description = "(Optional) IAM role for failure feedback."
  type        = string
  default     = ""
}

#------------------------------------------------------------------------------
# Http
#------------------------------------------------------------------------------
variable "http_success_feedback_role_arn" {
  description = "(Optional) The IAM role permitted to receive success feedback for this topic."
  type        = string
  default     = ""
}

variable "http_success_feedback_sample_rate" {
  description = "(Optional) Percentage of success to sample."
  type        = string
  default     = ""
}

variable "http_failure_feedback_role_arn" {
  description = "(Optional) IAM role for failure feedback."
  type        = string
  default     = ""
}

#------------------------------------------------------------------------------
# Lambda
#------------------------------------------------------------------------------
variable "lambda_success_feedback_role_arn" {
  description = "(Optional) The IAM role permitted to receive success feedback for this topic."
  type        = string
  default     = ""
}

variable "lambda_success_feedback_sample_rate" {
  description = "(Optional) Percentage of success to sample."
  type        = string
  default     = ""
}

variable "lambda_failure_feedback_role_arn" {
  description = "(Optional) IAM role for failure feedback."
  type        = string
  default     = ""
}

#------------------------------------------------------------------------------
# SQS
#------------------------------------------------------------------------------
variable "sqs_success_feedback_role_arn" {
  description = "(Optional) The IAM role permitted to receive success feedback for this topic."
  type        = string
  default     = ""
}

variable "sqs_success_feedback_sample_rate" {
  description = "(Optional) Percentage of success to sample."
  type        = string
  default     = ""
}

variable "sqs_failure_feedback_role_arn" {
  description = "(Optional) IAM role for failure feedback."
  type        = string
  default     = ""
}
