"connectorConfiguration": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector"",
        "tasks.max": "1",
        "database.hostname": "dev-usp.cluster-cpewhy546lbt.us-east-1.rds.amazonaws.com",
        "database.port": "5432",
        "database.user": "root",
        "database.password": "zQjbgXpPRtoyhshzcdI3",
        "database.server.name": "postgres",
        "database.include.list": "phoenix-dev",
        "database.history.consumer.security.protocol": "SASL_SSL",
        "database.history.consumer.sasl.mechanism": "AWS_MSK_IAM",
        "database.history.consumer.sasl.jaas.config": "software.amazon.msk.auth.iam.IAMLoginModule required;",
        "database.history.consumer.sasl.client.callback.handler.class": "software.amazon.msk.auth.iam.IAMClientCallbackHandler",
        "database.history.producer.security.protocol": "SASL_SSL",
        "database.history.producer.sasl.mechanism": "AWS_MSK_IAM",
        "database.history.producer.sasl.jaas.config": "software.amazon.msk.auth.iam.IAMLoginModule required;",
        "database.history.producer.sasl.client.callback.handler.class": "software.amazon.msk.auth.iam.IAMClientCallbackHandler",
        "include.schema.changes": "true"
        "table.include.list": "public.tutor",
        "column.include.list": "public.tutor.id,public.tutor.email,public.tutor.status",
        "transforms": "reroute,filter",
        "transforms.filter.type": "io.debezium.transforms.Filter",
        "transforms.filter.language": "jsr223.groovy",
        "transforms.filter.condition": "value.op != 'd' && (value.before == null || value.before.status != value.after.status || value.before.email != value.after.email)",
        "transforms.reroute.type": "io.debezium.transforms.ByLogicalTableRouter",
        "transforms.reroute.topic.regex": "(.*)",
        "transforms.reroute.topic.replacement": "tutor_history"
    }